sample added
SyncfusionExamples/DocIO-Examples pull request #101
Opened 2023-06-09 12:17 UTC by Venkateshmuruganandam

2023-06-13 15:51 UTC, MohanaselvamJothi requested changes

2023-06-14 06:44 UTC, Venkateshmuruganandam commented on Word-to-Image-conversion/Convert-Word-to-image/.NET-MAUI/Convert-Word-Document-to-Image/Convert-Word-Document-to-Image.csproj.user
> +<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
updated

2023-06-14 06:50 UTC, Venkateshmuruganandam commented on Word-to-Image-conversion/Convert-Word-to-image/WindowForms/Convert-Word-Document-to-Image/Form1.cs
> +            System.Diagnostics.Process.Start(Path.GetFullPath(@"../../WordToImage.Jpeg"));
updated

2023-06-14 07:59 UTC, MohanaselvamJothi approved these changes

2023-06-14 07:59 UTC, merged