Sample Added
SyncfusionExamples/DocIO-Examples pull request #117
Opened 2023-07-12 07:10 UTC by Venkateshmuruganandam

Hi All,
Sample added for following platform.

Regards
Venkatesh

2023-07-12 14:29 UTC, MohanaselvamJothi requested changes

2023-07-12 14:29 UTC, MohanaselvamJothi commented on Getting-Started/AWS/AWS_Lambda/Create-Word-Document/aws-lambda-tools-defaults.json
> +    "function-role"         : "arn:aws:iam::142887710098:role/LambdaRole",
change this

2023-07-13 05:13 UTC, Venkateshmuruganandam commented on Getting-Started/AWS/Console_Application/Create-Word-Document/Program.cs
> +        {
updated

2023-07-13 05:14 UTC, Venkateshmuruganandam commented on Getting-Started/Azure/Azure_App_Service/Create-Word-Document/Controllers/HomeController.cs
> +                stream.Position = 0;
updated

2023-07-13 05:31 UTC, Venkateshmuruganandam commented on Getting-Started/AWS/AWS_Lambda/Create-Word-Document/aws-lambda-tools-defaults.json
> +    "function-role"         : "arn:aws:iam::142887710098:role/LambdaRole",
updated.

2023-07-14 03:46 UTC, MohanaselvamJothi approved these changes

2023-07-14 03:46 UTC, merged