Committing Insert-comment-to-Word-document sample
SyncfusionExamples/DocIO-Examples pull request #121
Opened 2023-08-09 10:38 UTC by AkashArul26

Insert-comment-to-Word-document sample

2023-08-09 11:49 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-09-28 11:50 UTC, MohanaselvamJothi requested changes

2023-09-28 11:50 UTC, MohanaselvamJothi commented on Comments/Find-text-and-insert-comment/.NET/Insert-comment-to-Word-document/Program.cs
> +            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Path.GetFullPath(@"../../../Result.docx")) { UseShellExecute = true });
Remove this code

2023-09-28 12:04 UTC, AkashArul26 commented on Comments/Find-text-and-insert-comment/.NET/Insert-comment-to-Word-document/Program.cs
> +            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Path.GetFullPath(@"../../../Result.docx")) { UseShellExecute = true });
Removed that code

2023-09-28 12:12 UTC, MohanaselvamJothi approved these changes

2023-09-28 12:12 UTC, merged