ES-907669-Modify DocIO GitHub examples repository for document processing playground
SyncfusionExamples/DocIO-Examples pull request #223
Opened 2024-09-09 04:51 UTC by Yaminisrisf4389

Modify DocIO GitHub examples repository for document processing playground

2024-09-09 19:16 UTC, LokeshBaskar requested changes
Please address the feedback

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Data/Input.docx
@Yaminisrisf4389, why bin folders changes are committed. Please check and update the properly.

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Output/.gitkeep
why bin folders changes are committed. Please check and update the properly.

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Output/Sample.docx
why bin folders changes are committed. Please check and update the properly.

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Get-list-value/.NET/Get-list-value/bin/Debug/net8.0/Data/Template.docx
why bin folders changes are committed. Please check and update the properly.

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Remove_all_page_breaks/.NET/Remove_all_page_breaks/Program.cs
> +using (FileStream inputStream = new FileStream(@"Data/Template.docx", FileMode.Open, FileAccess.Read))
Please use the Path.GetFullPath()

2024-09-09 19:16 UTC, LokeshBaskar commented on Paragraphs/Remove_all_page_breaks/.NET/Remove_all_page_breaks/Program.cs
> +        using (FileStream outputStream = new FileStream(@"Output/Output.docx", FileMode.Create, FileAccess.Write))
Please use the Path.GetFullPath()

2024-09-10 08:02 UTC, Yaminisrisf4389 commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Data/Input.docx
resolved

2024-09-10 08:03 UTC, Yaminisrisf4389 commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Output/.gitkeep
resolved

2024-09-10 08:17 UTC, Yaminisrisf4389 commented on Paragraphs/Apply-paragraph-formatting/.NET/Apply-paragraph-formatting/bin/Debug/net8.0/Output/Sample.docx
resolved

2024-09-10 08:17 UTC, Yaminisrisf4389 commented on Paragraphs/Get-list-value/.NET/Get-list-value/bin/Debug/net8.0/Data/Template.docx
resolved

2024-09-10 08:18 UTC, Yaminisrisf4389 commented on Paragraphs/Remove_all_page_breaks/.NET/Remove_all_page_breaks/Program.cs
> +using (FileStream inputStream = new FileStream(@"Data/Template.docx", FileMode.Open, FileAccess.Read))
added

2024-09-10 08:18 UTC, Yaminisrisf4389 commented on Paragraphs/Remove_all_page_breaks/.NET/Remove_all_page_breaks/Program.cs
> +        using (FileStream outputStream = new FileStream(@"Output/Output.docx", FileMode.Create, FileAccess.Write))
added

2024-09-10 08:42 UTC, LokeshBaskar approved these changes
No concerns

2024-09-10 09:33 UTC, MohanaselvamJothi approved these changes

2024-09-10 09:33 UTC, merged