Added apply left indent sample
SyncfusionExamples/DocIO-Examples pull request #238
Opened 2024-09-29 19:55 UTC by VijayadharshiniMathiyalagan

2024-09-30 14:52 UTC, LokeshBaskar requested changes

2024-09-30 14:52 UTC, LokeshBaskar commented on Paragraphs/Apply-indentation-for-import-content/.NET/Apply-indentation-for-import-content/Data/Temporary.docx
Remove unused file

2024-10-04 07:43 UTC, LokeshBaskar requested changes
Please address the feedback.

2024-10-04 07:43 UTC, LokeshBaskar commented on Word-to-PDF-Conversion/Replace-Excel-embedded-image-to-PNG/.NET/Replace-Excel-embedded-image-to-PNG/Program.cs
> +pdf.Save(outputStream);
Either dispose or use using statement

2024-10-04 07:43 UTC, LokeshBaskar commented on Word-to-PDF-Conversion/Replace-Excel-embedded-image-to-PNG/.NET/Replace-Excel-embedded-image-to-PNG/Program.cs
> +void ReplaceExcelToImage(WordDocument wordDocument)
XML comments

2024-10-04 10:20 UTC, VijayadharshiniMathiyalagan commented on Word-to-PDF-Conversion/Replace-Excel-embedded-image-to-PNG/.NET/Replace-Excel-embedded-image-to-PNG/Program.cs
> +pdf.Save(outputStream);
addressed

2024-10-04 12:39 UTC, MohanaselvamJothi approved these changes

2024-10-04 12:40 UTC, merged