Added sample to delete specific content from the Word document
SyncfusionExamples/DocIO-Examples pull request #260
Opened 2024-10-21 11:48 UTC by VijayadharshiniMathiyalagan

Description:'
Added sample to delete specific content from the Word document

2024-10-23 12:41 UTC, Suriya-Balamurugan requested changes

2024-10-23 12:41 UTC, Suriya-Balamurugan commented on Word-document/Delete-specific-content/Delete-specific-content/Program.cs
> + void DeleteContentInWordDocument(int startIndex, int endIndex, WordDocument document)
Modify the method name.
DeleteSpecificContent()

2024-10-24 12:31 UTC, Suriya-Balamurugan approved these changes
No concerns.

2024-10-25 05:01 UTC, MohanaselvamJothi approved these changes

2024-10-25 05:01 UTC, merged