Apply-bold-formatting-to-the-content-between-placeholders
SyncfusionExamples/DocIO-Examples pull request #311
Opened 2024-12-17 03:05 UTC by DharanyaSakthivel-SF4210

Apply-bold-formatting-to-the-content-between-placeholders

2024-12-31 10:31 UTC, MohanaselvamJothi requested changes

2024-12-31 10:31 UTC, MohanaselvamJothi commented on Find-and-Replace/Apply-bold-between-placeholder/Apply-bold-between-placeholder/Program.cs
> +    Regex regex = new Regex("<b>(.*?)</b>");
Modify the template enclosed with <b> </b> only

2025-01-02 05:44 UTC, DharanyaSakthivel-SF4210 commented on Find-and-Replace/Apply-bold-between-placeholder/Apply-bold-between-placeholder/Program.cs
> +    Regex regex = new Regex("<b>(.*?)</b>");
Modified in template

2025-01-02 08:07 UTC, MohanaselvamJothi approved these changes

2025-01-02 08:07 UTC, merged