Adding sample to get image from URL and insert into Word document while performing mail merge
SyncfusionExamples/DocIO-Examples pull request #57
Opened 2023-01-17 11:26 UTC by elizabethatienoo

Added KB sample. The sample is:
Mail-merge-using-image-from-URL

2023-01-17 11:49 UTC, Suriya-Balamurugan requested changes

2023-01-17 11:49 UTC, Suriya-Balamurugan commented on Mail-Merge/Mail-merge-using-image-from-URL/.NET-Standard/Mail-merge-using-image-from-URL/Program.cs
> +                    //Executes the mail merge with groups.
Modify the xml comment as below

//Executes the mail merge.

2023-01-17 11:49 UTC, Suriya-Balamurugan commented on Mail-Merge/Mail-merge-using-image-from-URL/.NET-Standard/Mail-merge-using-image-from-URL/Program.cs
> +}
Mail-Merge/Mail-merge-using-image-from-URL/.NET-Standard/Mail-merge-using-image-from-URL/Data/Logo.png

Remove this local image from sample.

2023-01-19 08:59 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-01-19 09:13 UTC, MohanaselvamJothi approved these changes

2023-01-19 09:13 UTC, merged