Added samples for Section, Content-Control and Footnotes and Endnotes
SyncfusionExamples/DocIO-Examples pull request #6
Opened 2022-02-24 15:22 UTC by ManikandanRavichandranSync

Added samples for Section, Content-Control and Footnotes and Endnotes

2022-02-28 05:27 UTC, MohanaselvamJothi requested changes

2022-03-01 07:58 UTC, ManikandanRavichandranSync commented on Content-Controls/Edit-content-control-text/.NET-Standard/Edit-content-control-text/Program.cs
> +        private static void ReplaceTextWithInlineContentControl(string text, InlineContentControl inlineContentControl)
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Footnotes-and-Endnotes/Edit-footnotes-and-endnotes/.NET-Standard/Edit-footnotes-and-endnotes/Program.cs
> +                            {
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Content-Controls/Edit-content-control-text/.NET-Standard/Edit-content-control-text/Program.cs
> +                        if(inlineContentControl.ContentControlProperties.Title == "ReplaceText")
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Content-Controls/Edit-content-control-text/.NET-Standard/Edit-content-control-text.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Edit-content-control-text", "Edit-content-control-text\Edit-content-control-text.csproj", "{AE9996D9-17F0-4A69-AB1D-CA10E8605CF7}"
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Word-document/Split-by-heading/.NET-Standard/Split-by-heading/Program.cs
> +                        {
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Word-document/Split-by-heading/.NET-Standard/Split-by-heading/Program.cs
> +                                        //Saves the Word document to  MemoryStream
Addressed the feedback

2022-03-01 07:59 UTC, ManikandanRavichandranSync commented on Word-document/Split-by-section/.NET-Standard/Split-by-section/Program.cs
> +                            newDocument.Sections.Add(section.Clone());
Addressed the feedback

2022-03-01 08:00 UTC, ManikandanRavichandranSync commented on Word-document/Split-by-heading/.NET-Standard/Split-by-heading/Program.cs
> +                                else if (para.StyleName != "Heading 1" && newDocument != null)
Addressed the feedback

2022-03-01 08:00 UTC, ManikandanRavichandranSync commented on Footnotes-and-Endnotes/Edit-footnotes-and-endnotes/.NET-Standard/Edit-footnotes-and-endnotes.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Edit-footnotes-and-endnotes", "Edit-footnotes-and-endnotes\Edit-footnotes-and-endnotes.csproj", "{8EC56111-D683-4E69-8559-4142B0199648}"
Addressed the feedback

2022-03-01 08:00 UTC, ManikandanRavichandranSync commented on Footnotes-and-Endnotes/Edit-footnotes-and-endnotes/.NET-Standard/Edit-footnotes-and-endnotes/Program.cs
> +            {
Addressed the feedback

2022-03-01 08:00 UTC, ManikandanRavichandranSync commented on Footnotes-and-Endnotes/Edit-footnotes-and-endnotes/.NET-Standard/Edit-footnotes-and-endnotes/Program.cs
> +        /// <param name="document"></param>
Addressed the feedback

2022-03-01 08:00 UTC, ManikandanRavichandranSync commented on Footnotes-and-Endnotes/Edit-footnotes-and-endnotes/.NET-Standard/Edit-footnotes-and-endnotes/Program.cs
> +                            if (paragraph.ChildEntities[j] is WFootnote)
Addressed the feedback

2022-03-01 08:01 UTC, ManikandanRavichandranSync commented on Word-document/Split-by-heading/.NET-Standard/Split-by-heading/Program.cs
> +                    inputStream.Dispose();
Addressed the feedback

2022-03-01 10:07 UTC, sivasubramanv approved these changes

2022-03-01 10:09 UTC, sivasubramanv approved these changes

2022-03-01 10:14 UTC, sivasubramanv approved these changes

2022-03-01 10:14 UTC, sivasubramanv commented
Commit

2022-03-01 10:16 UTC, merged