Added sample to reset page numbering after each record
SyncfusionExamples/DocIO-Examples pull request #67
Opened 2023-02-02 12:39 UTC by elizabethatienoo

Added KB sample. The sample is:
Reset-page-numbers-after-each-record

2023-02-15 04:58 UTC, Suriya-Balamurugan requested changes

2023-02-15 04:58 UTC, Suriya-Balamurugan commented on Paragraphs/Resize-list-character/.NET-Standard/Resize-list-character/Program.cs
> +        /// Iterate through source document section.
Iterate through the headers and footers.

2023-02-15 04:58 UTC, Suriya-Balamurugan commented on Paragraphs/Resize-list-character/.NET-Standard/Resize-list-character/Program.cs
> +                    foreach (WSection section in document.Sections)
Iterate through the each section of the Word document.

2023-02-15 04:58 UTC, Suriya-Balamurugan commented on Paragraphs/Resize-list-character/.NET-Standard/Resize-list-character/Program.cs
> +                        //Accesse the Body of section where all the contents in document are apart.
Access

2023-02-15 04:58 UTC, Suriya-Balamurugan commented on Paragraphs/Resize-list-character/.NET-Standard/Resize-list-character/Program.cs
> +                        IterateHeaderFooter(section);
//Iterate through the headers and footers

2023-02-20 14:48 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-20 15:52 UTC, Suriya-Balamurugan approved these changes

2023-02-21 05:11 UTC, MohanaselvamJothi approved these changes

2023-02-21 05:11 UTC, merged