Adding samples of content control
SyncfusionExamples/DocIO-Examples pull request #68
Opened 2023-02-09 06:55 UTC by sharonaumao

Added KB samples. The samples are

- Remove-placeholder-of-empty-meta-property
-

2023-02-13 10:39 UTC, Suriya-Balamurugan requested changes

2023-02-13 10:39 UTC, Suriya-Balamurugan commented on HTML-conversions/Save-image-in-folder-in-Word-to-HTML/.NET-Standard/Save-image-in-folder-in-Word-to-HTML/Program.cs
> +            string imagepath = @"D:\Temp\Image1.png";
This code is not generic. If your Word document contains multiple images, all the images saves as same name and the last image only used in the HTML

Use generic solution for image path. Then only all the images are saved as new name and all those images are used in the HTML.

2023-02-15 05:45 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-02-15 06:00 UTC, MohanaselvamJothi approved these changes

2023-02-15 06:00 UTC, merged