Adding sample of Applying base styles to table styles
SyncfusionExamples/DocIO-Examples pull request #71
Opened 2023-03-01 12:30 UTC by sharonaumao

Added KB sample. The sample is

- Apply-base-style-for-table

2023-03-03 09:49 UTC, MohanaselvamJothi requested changes

2023-03-03 09:49 UTC, MohanaselvamJothi commented on Markdown-to-Word-conversion/Customize-image/.NET-Standard/Customize-image/Program.cs
> +                args.ImageStream = new FileStream("Image_1.png", FileMode.Open);
Not found image 1 and image 2 files. Could you please ensure the sample is working fine

2023-03-07 11:56 UTC, Suriya-Balamurugan approved these changes
I don't have any concerns in this code changes.

2023-03-07 12:41 UTC, MohanaselvamJothi approved these changes

2023-03-07 12:42 UTC, merged